name: mobile_tech_app
description: Mobile tech application.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.1.0
  cached_network_image: ^3.1.0
  connectivity: ^3.0.6
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
